# Generated by Django 3.1.2 on 2021-02-08 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210208_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('post', models.TextField()),
                ('image', models.ImageField(upload_to='static/blogimage')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 16, 47, 20, 780432))),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
