# Generated by Django 3.1.2 on 2021-02-08 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210208_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 16, 48, 8, 379985)),
        ),
    ]
